spring.application.name=MQTT_GatwayConfig

server.port=8088

mqtt.broker-url=tcp://192.168.20.118:1883
mqtt.client-id=mqtt-websocket-bridge
mqtt.topic=device/status
mqtt.username=qaweb
mqtt.password=qaweb@123
#Dev topics
#mqtt.topics[0]=live/1/562/vision-inference


jwt.secret=1234567890123456789012345678901234567890123456789012345678901234

#logging.level.org.eclipse.paho=DEBUG
#logging.level.org.eclipse.paho.client.mqttv3=DEBUG